# ------------------------------------------------------------------------------
# Copyright (c) Microsoft
# Licensed under the MIT License.
# Written by Bin Xiao (Bin.Xiao@microsoft.com)
# ------------------------------------------------------------------------------

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from yacs.config import CfgNode as CN

ACSALNET = CN()
ACSALNET.PRETRAINED_LAYERS = ['*']
ACSALNET.FINAL_CONV_KERNEL = 1

ACSALNET.FPN_CHANNEL_NUM = 256
ACSALNET.MSFE_OUT_CHANNEL_NUM = 32
ACSALNET.MSFE_INNER_CHANNEL_NUM = [256, 256, 256, 256]
ACSALNET.USE_HIGH_RES_PATH = False

ACSALNET.STAGE2 = CN()
ACSALNET.STAGE2.NUM_BLOCKS = 4
ACSALNET.STAGE2.SCALES = [4, 8]
ACSALNET.STAGE2.NUM_CHANNELS = [32, 64]
ACSALNET.STAGE2.BLOCK = 'BASIC'
ACSALNET.STAGE2.FUSE_METHOD = 'SUM'

ACSALNET.STAGE3 = CN()
ACSALNET.STAGE3.NUM_MODULES = 1
ACSALNET.STAGE3.NUM_BLOCKS = 4
ACSALNET.STAGE3.SCALES = [4, 16]
ACSALNET.STAGE3.NUM_CHANNELS = [32, 128]
ACSALNET.STAGE3.BLOCK = 'BASIC'
ACSALNET.STAGE3.FUSE_METHOD = 'SUM'

ACSALNET.STAGE4 = CN()
ACSALNET.STAGE4.NUM_MODULES = 1
ACSALNET.STAGE4.NUM_BLOCKS = 4
ACSALNET.STAGE4.SCALES = [4, 32]
ACSALNET.STAGE4.NUM_CHANNELS = [32, 256]
ACSALNET.STAGE4.BLOCK = 'BASIC'
ACSALNET.STAGE4.FUSE_METHOD = 'SUM'

ACSALNET.DECONV = CN()
ACSALNET.DECONV.NUM = 2
ACSALNET.DECONV.NUM_CHANNELS = [32, 32]
ACSALNET.DECONV.KERNELS = [4, 4]
ACSALNET.DECONV.EXTRA_LAYERS = 0

MODEL_EXTRAS = {
    'acsalnet': ACSALNET,
}
